services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "5002:5002"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  web:
    build: .
    command: >
      gunicorn -k eventlet
               -w 1 -b 0.0.0.0:5000 chat:application
    volumes:
      - ./:/app
    expose:
      - "5000"


