services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "5002:5002"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  web:
    image: ai_sessions-web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - /media/anandas/colan_storage/docker/ai_session:/data
    command: >
      gunicorn -k eventlet
               -w 1 -b 0.0.0.0:5000 src:application
    ports:
      - "5000:5000"


